---
# https://docs.linuxserver.io/images/docker-github-desktop
version: "2.1"
services:
  github-desktop:
    image: lscr.io/linuxserver/github-desktop:latest
    container_name: github-desktop
    cap_add:
      - IPC_LOCK
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
