name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly

      - name: Build
        run: |
          cargo build --verbose

      - name: Run tests
        run: |
          cargo test --verbose

      - name: Run Analysis
        continue-on-error: true
        run: |
          cargo run -- compose -f all -p ./examples

  container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag quibble:dev

      - name: Run container
        run: |
          docker run --rm --name quibble quibble:dev


